osg_devices:
    resource: "@OSGDevicesBundle/Controller/"
    type:     annotation
    prefix:   /

osg_arduinos:
    resource: "@OSGArduinosBundle/Controller/"
    type:     annotation
    prefix:   /

osg_home_page:
    resource: "@OSGHomePageBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
